context:
  version: 0.3.3

package:
  name: xeus-javascript
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus-javascript/archive/refs/tags/{{ version }}.tar.gz
  sha256: 910ddcc7eb6a739a790f71368ea4fea3c89b6619157285dbed1ed45a4060e0d7

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - nlohmann_json
    - xeus-lite >=2.0.0
    - xeus >=4.0.2,<5.0
    - xtl >=0.7

test:
  commands:
    - sel(emscripten): test -f $PREFIX/bin/xjavascript.wasm
    - sel(emscripten): test -f $PREFIX/bin/xjavascript.js

about:
  home: https://github.com/jupyter-xeus/xeus-javascript
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-javascript
  doc_url: https://github.com/jupyter-xeus/xeus-javascript
  dev_url: https://github.com/jupyter-xeus/xeus-javascript

extra:
  recipe-maintainers:
    - DerThorsten
