context:

  version: 4.0.2


package:
  name: xeus
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus/archive/refs/tags/{{ version }}.tar.gz
  sha256: a7876f1a0c994b300515e7f95baa948ce8fbd6f1afb72739eb4a4916341843ac

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - nlohmann_json
    - xtl

test:
  commands:
    - sel(emscripten): test -f $PREFIX/lib/libxeus.a
    - sel(emscripten): test -f $PREFIX/include/xeus/xeus.hpp

about:
  home: https://github.com/jupyter-xeus/xeus
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus
  doc_url: https://github.com/jupyter-xeus/xeus
  dev_url: https://github.com/jupyter-xeus/xeus

extra:
  recipe-maintainers:
    - DerThorsten
    - JohanMabille
